---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environments-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-istio
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/dev
  prune: true
  wait: false
