apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - go-app.yaml
  - istio.yaml
  - jetstack.yaml
  - kubernetes-sigs.yaml
  - metallb.yaml
  - externalsecrets.yaml
