---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environments
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/ephemeral
  prune: true
  wait: false
  timeout: 5m
