apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - sealed-secrets
  - external-secrets
  - external-secrets-config
  - cert-manager
  - cert-manager-config
  - istio
  - metallb
  - external-dns
